package server;

public enum ResponseType {
    CONNECTION_ESTABLISHED,
    CONNECTION_TERMINATED,
    PLAYER_QUEUED,
    GAME_STARTED,
    CHOOSEN_CATEGORY,
    GET_QUESTION,
    PLAYER_ONE_DONE,
    PLAYER_TWO_TURN,
    GAME_DONE;
}
