package server;

public enum ResponseType {
    CONNECTION_ESTABLISHED,
    CONNECTION_TERMINATED,
    PLAYER_QUEUED,
    GAME_STARTED,
    CHOOSEN_CATEGORY,
    GET_QUESTION,
    MY_TURN_CHOOSING,
    MY_TURN_ANSWERING,
    WAITING,
    GAME_DONE;
}
