package Client;

public enum RequestType {
    CONNECT_REQUEST,
    DISCONNECT,
    FIND_OPPONENT_REQUEST,
    START_GAME,
    CATEGORY_TYPE_REQUEST,
    PLAYER1_PLAYING,
    PLAYER_ONE_DONE,
    MY_SCORE,
    ROUND_FINISHED;
}